[package]
name = "kbdi"
version = "0.2.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
publish = false

[dependencies.winapi]
git = "https://github.com/bbqsrc/winapi-rs"
branch = "move-kernel32-nls-funcs"
features = ["everything"]

[dependencies.winreg]
version = "0.4"
default-features = false
features = []

[dependencies.clap]
version = "2.24.1"
default-features = false
features = []

[profile.release]
lto = true
panic = "abort"
